import 'controller/forgot_password_controller.dart';import 'package:flutter/material.dart';import 'package:genescor/core/app_export.dart';import 'package:genescor/widgets/app_bar/appbar_image.dart';import 'package:genescor/widgets/app_bar/appbar_subtitle.dart';import 'package:genescor/widgets/app_bar/custom_app_bar.dart';import 'package:genescor/widgets/custom_elevated_button.dart';import 'package:genescor/widgets/custom_text_form_field.dart';class ForgotPasswordScreen extends GetWidget<ForgotPasswordController> {const ForgotPasswordScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, backgroundColor: appTheme.whiteA700, appBar: CustomAppBar(leadingWidth: getHorizontalSize(43), leading: AppbarImage(svgPath: ImageConstant.imgArrowleft, margin: getMargin(left: 19, top: 14, bottom: 17), onTap: () {onTapArrowleftone();}), centerTitle: true, title: AppbarSubtitle(text: "msg_forgot_password".tr)), body: Container(width: double.maxFinite, padding: getPadding(left: 15, top: 20, right: 15, bottom: 20), child: Column(crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.start, children: [Container(width: getHorizontalSize(370), margin: getMargin(left: 4, right: 23), child: Text("msg_don_t_worry_it".tr, maxLines: 2, overflow: TextOverflow.ellipsis, style: theme.textTheme.bodyLarge!.copyWith(height: 1.44))), Padding(padding: getPadding(left: 4, top: 33), child: Text("lbl_email".tr, style: theme.textTheme.titleMedium)), CustomTextFormField(controller: controller.emailController, margin: getMargin(left: 4, top: 10), hintText: "lbl_enter".tr, hintStyle: CustomTextStyles.bodyMediumBluegray500_1, textInputAction: TextInputAction.done), CustomElevatedButton(text: "lbl_submit".tr, margin: getMargin(left: 4, top: 75)), Align(alignment: Alignment.center, child: Padding(padding: getPadding(top: 25, bottom: 5), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(svgPath: ImageConstant.imgArrowleftGray900, height: getSize(20), width: getSize(20)), Padding(padding: getPadding(left: 10, top: 3), child: Text("lbl_back_to_sign_in".tr, style: CustomTextStyles.bodySmallGray900_1))])))])))); } 


/// Navigates to the previous screen.
///
/// When the action is triggered, this function uses the [Get] package to 
/// navigate to the previous screen in the navigation stack.
onTapArrowleftone() { Get.back(); } 
 }
